### DISCUSSION TITLE
Markdown Card to show Octopus account details

### DISCUSSION THREAD

**Discussion by thecem** [thecem/octopus_germany#18] [Show and tell]
![grafik](https://github.com/user-attachments/assets/45c4d402-5a41-4f95-9e92-12e0314266dd)

<details>

<summary>Octopus Account Markup Card</summary>

```yaml
{%- set sensor_name = 'sensor.octopus_a_12345678_intelligent_dispatching' %}

## Octopus
- **Account:** {{ state_attr(sensor_name, 'account_number') }}
- **Guthaben:** {{ state_attr(sensor_name, 'electricity_balance') }}
{% set products = state_attr(sensor_name, 'products') %}

### Aktuelle Tarife
{%- for p in products %}

#### - {{ p.name }}
- **Code:** {{ p.code }}
- **Beschreibung:** {{ p.description }}
- **Bruttopreis:** {{ p.gross_rate | replace('.', ',') }} ct/kWh
- **Gültig:** {{ p.valid_from[:10] }} bis {{ p.valid_to[:10] }}
{% endfor %}

### Meter
- **MaLo:** {{ state_attr(sensor_name, 'malo_number') }}
- **MeLo:** {{ state_attr(sensor_name, 'melo_number') }}

{%- set meter = state_attr(sensor_name, 'meter') %}
{%- set number = meter.number %}
- **ID:** {{ meter.id }}
- **Type:** {{ meter.meterType }}
- **Number:** {{ number }}
- **ReceiveMeterData:** {{ meter.shouldReceiveSmartMeterData }}
```

</details>

<details>

<summary>Octopus Account Markup Card >Version 0.0.34 </summary>

```yaml
{%- set sensor_name = 'sensor.octopus_a_12345678_electricity_price' %}

## Octopus
- **Account:** {{ state_attr(sensor_name, 'account_number') }}
- **Guthaben:** {{ state_attr(sensor_name, 'electricity_balance') }}

### Tarif
- **Name:** {{ state_attr(sensor_name, 'name') }}
- **Code:** {{ state_attr(sensor_name, 'code') }}
- **Beschreibung:** {{ state_attr(sensor_name, 'description') }}
- **Bruttopreis:** {{ states(sensor_name) }} ct/kWh
- **Gültig:** {{ as_datetime(state_attr(sensor_name, 'valid_from')).strftime('%d.%m.%Y') }} bis {{ as_datetime(state_attr(sensor_name, 'valid_to')).strftime('%d.%m.%Y') }}

### Zähler
- **MaLo:** {{ state_attr(sensor_name, 'malo_number') }}
- **MeLo:** {{ state_attr(sensor_name, 'melo_number') }}
- **ID:** {{ state_attr(sensor_name, 'meter_id') }}
- **Typ:** {{ state_attr(sensor_name, 'meter_type') }}
- **Nummer:** {{ state_attr(sensor_name, 'meter_number') }}
```

</details>

![grafik](https://github.com/user-attachments/assets/1add2a64-ec1e-4079-a5b0-4a6fac31f635)

<details>

<summary>Device Markup Card</summary>

```yaml
{%- set sensor_name = 'sensor.octopus_a_12345678_intelligent_dispatching' %}
{%- set switch_name = 'switch.octopus_a_12345678_device_smart_control' %}



{% set device = state_attr(sensor_name, 'devices')[0] %}
{% set schedules = device.preferences.schedules %}
{% set day_map = {
  'MONDAY': 'Mo',
  'TUESDAY': 'Di',
  'WEDNESDAY': 'Mi',
  'THURSDAY': 'Do',
  'FRIDAY': 'Fr',
  'SATURDAY': 'Sa',
  'SUNDAY': 'So'
} %}

### {{ device.name }} ({{ device.model }}, {{ device.battery_size }} kWh)

**Smart Charging:** {{ '🟢' if states(switch_name) else '🔴'}}
**Status:** {{ device.status }}    
**Modus:** {{ device.preferences.mode }}  
**Provider:** {{ device.provider }}  


---

#### 🗓️ Ladeplan

{% set ns = namespace(schedule_map={}) %}
{% for s in schedules %}
  {% set key = s.time[:5] ~ '|' ~ ('%.0f' % s.max) %}
  {% if key in ns.schedule_map %}
    {% set ns.schedule_map = ns.schedule_map | combine({ key: ns.schedule_map[key] + [day_map[s.day]] }) %}
  {% else %}
    {% set ns.schedule_map = ns.schedule_map | combine({ key: [day_map[s.day]] }) %}
  {% endif %}
{% endfor %}



| Tage | Zeit | Ziel-SoC (%) |
|:---|:---|:---:|
{% for key, days in ns.schedule_map | dictsort %}
    {%- set parts = key.split('|') -%}
    | {{ days | join(', ') }} | {{ parts[0] }} | {{ parts[1] }} |
{% endfor %}



{% if ns.schedule_map | length == 1 %}
✅ **Einheitlicher Ladeplan:**  
Täglich um **{{ schedules[0].time[:5] }} Uhr** auf **{{ "%.0f"|format(schedules[0].max) }} %** laden.
{% else %}
> ⚠️ Unterschiedliche Ladepläne je Wochentag.
{% endif %}

---

#### Planned Dispatches

| Start | Ladung (kWh) | Ende | Quelle | Standort |
|:---:|:---:|:---:|:---:|:---:|
{% for item in state_attr(sensor_name, 'planned_dispatches') -%}
| {{ as_timestamp(item.start) | timestamp_custom('%d.%m.%y %H:%M', true) }} | {{ item.charge_kwh if item.charge_kwh is not none else '-' }} | {{ as_timestamp(item.end) | timestamp_custom('%d.%m.%y %H:%M', true) }} |  {{ item.source if item.source else '-' }} | {{ item.location if item.location else '-' }} |
{% endfor %}

---

#### Completed Dispatches

| Start | Ladung (kWh) | Ende | Quelle | Standort |
|:---:|:---:|:---:|:---:|:---:|
{% for item in state_attr(sensor_name, 'completed_dispatches') -%}
| {{ as_timestamp(item.start) | timestamp_custom('%d.%m.%y %H:%M', true) }} | {{ item.charge_kwh if item.charge_kwh is not none else '-' }} | {{ as_timestamp(item.end) | timestamp_custom('%d.%m.%y %H:%M', true) }} |  {{ item.source if item.source else '-' }} | {{ item.location if item.location else '-' }} |
{% endfor %}
```

</details>

<details>

<summary>Device Markup Card >Version 0.0.35 </summary>

```yaml
{%- set sensor_name = 'binary_sensor.octopus_a_12345678_intelligent_dispatching' %}
{%- set switch_name = 'switch.octopus_a_12345678_device_smart_control' %}



{% set device = state_attr(sensor_name, 'devices')[0] %}
{% set schedules = device.preferences.schedules %}
{% set day_map = {
  'MONDAY': 'Mo',
  'TUESDAY': 'Di',
  'WEDNESDAY': 'Mi',
  'THURSDAY': 'Do',
  'FRIDAY': 'Fr',
  'SATURDAY': 'Sa',
  'SUNDAY': 'So'
} %}

### {{ device.name }} ({{ device.model }}, {{ device.battery_size }} kWh)

**Smart Charging:** {{ '🟢' if states(switch_name) else '🔴'}}
**Status:** {{ device.status }}    
**Modus:** {{ device.preferences.mode }}  
**Provider:** {{ device.provider }}  


---

#### 🗓️ Ladeplan

{% set ns = namespace(schedule_map={}) %}
{% for s in schedules %}
  {% set key = s.time[:5] ~ '|' ~ ('%.0f' % s.max) %}
  {% if key in ns.schedule_map %}
    {% set ns.schedule_map = ns.schedule_map | combine({ key: ns.schedule_map[key] + [day_map[s.day]] }) %}
  {% else %}
    {% set ns.schedule_map = ns.schedule_map | combine({ key: [day_map[s.day]] }) %}
  {% endif %}
{% endfor %}



| Tage | Zeit | Ziel-SoC (%) |
|:---|:---|:---:|
{% for key, days in ns.schedule_map | dictsort %}
    {%- set parts = key.split('|') -%}
    | {{ days | join(', ') }} | {{ parts[0] }} | {{ parts[1] }} |
{% endfor %}



{% if ns.schedule_map | length == 1 %}
✅ **Einheitlicher Ladeplan:**  
Täglich um **{{ schedules[0].time[:5] }} Uhr** auf **{{ "%.0f"|format(schedules[0].max) }} %** laden.
{% else %}
> ⚠️ Unterschiedliche Ladepläne je Wochentag.
{% endif %}

---

#### Planned Dispatches

| Start | Ladung (kWh) | Ende | Quelle | Standort |
|:---:|:---:|:---:|:---:|:---:|
{% for item in state_attr(sensor_name, 'planned_dispatches') -%}
| {{ as_timestamp(item.start) | timestamp_custom('%d.%m.%y %H:%M', true) }} | {{ item.charge_kwh if item.charge_kwh is not none else '-' }} | {{ as_timestamp(item.end) | timestamp_custom('%d.%m.%y %H:%M', true) }} |  {{ item.source if item.source else '-' }} | {{ item.location if item.location else '-' }} |
{% endfor %}

---

#### Completed Dispatches

| Start | Ladung (kWh) | Ende | Quelle | Standort |
|:---:|:---:|:---:|:---:|:---:|
{% for item in state_attr(sensor_name, 'completed_dispatches') -%}
| {{ as_timestamp(item.start) | timestamp_custom('%d.%m.%y %H:%M', true) }} | {{ item.charge_kwh if item.charge_kwh is not none else '-' }} | {{ as_timestamp(item.end) | timestamp_custom('%d.%m.%y %H:%M', true) }} |  {{ item.source if item.source else '-' }} | {{ item.location if item.location else '-' }} |
{% endfor %}
```

</details>

**Comment by cschlipf** [comment]
Sehr cool!

**Reply by typxxi** [reply]
Hut ab !

**<ins>Für alle zum GUTHABEN Nachrechnen** 

Das Guthaben wird angesammelt durch die Abschlagszahlungen und die offenen Boni.
Bei uns sind das aktuell 7 Monate , was 802 € wären, aber 1252€ ausgewiesen. 
Die 450€ müssen aus den Abschluss und Empfehlungsboni stammen, was 250€ + 100€ waren sowie 50€ Bonus von der Hotline nach Smartladeproblemen und 2x 10€ vom Laden, bevor wir das Smartmeter hatten. 
Die übrigen 30€ müssen dann andere Boni sein. 

Das ist relativ sicher, weil die Summe bis auf den Cent genau stimmt, wenn ich 30€ für einen weiteren Bonus, an den ich mich gerad nicht erinnere, einrechne. 

Die Boni werden dann im 2 Jahresvertrag nach dem 1. Jahr abgerechnet. 

Hier waren es gut 7,5 Monate von Vertrags- und Lieferungsbeginn 1.4. bis das Smartmeter eingebaut (8.10.2025) war und die Daten auch bei Octopus in der App angekommen sind, so dass man den Tagesverbrauch ab dem Folgetag sehen kann.

Da war Tibber mit deren Pulse wesentlich besser aufgestellt, weil man Echtzeitdaten hatte. Aber das geht über Home Assistant auch anders.

**Reply by cschlipf** [reply]
Schau doch einfach in die App. Dort ist jeder einzelner Bonus, jede einzelne Empfehlung und jeder einzelne Abschlag aufgelistet.

**Reply by typxxi** [reply]
> Schau doch einfach in die App. Dort ist jeder einzelner Bonus, jede einzelne Empfehlung und jeder einzelne Abschlag aufgelistet.

hier nicht wirklich. Hier fehlen die - zumindest noch. Ich habe nur 2 via Nachrichten erhalten. 
DANKE

**Comment by typxxi** [comment]
1.
Ich bin mir nicht sicher, aber es scheint hier zu haken (Problem taucht mehrfach im Code auf)

` {{ item.charge_kwh if item.charge_in_kwh is not none else '-' }}`

das Attribut heißt bei mir auch item.charge_kwh 

**<ins>ABER:** die Prüfung nutzt ein wohl nicht existierendes Attribut, wo noch "_in_" enthalten ist : if item.charge_in_kwh
Bei mir steht aber in den Rohdaten eine 0 kWh für alle Ladezeiten von heut Nacht drin, obschon ich weiß, dass mit 7 kW geladen worden ist und so grob 6 kWh rein gegangen sein sollten. 
Das wiederum ist wohl aber ein Octopus Problem oder der Wallbox, dass die nix zurückreported.

2.
und dann ist mir aufgefallen, dass Octopus meine "PULSAR PLUS" wohl scheinbar als "PULSAR MAX" führt, obschon ich damals PLUS ausgewählt hatte bei der Bestellung und auch bei der Einrichtung, denn die hatten damals eine Kompatibiltätsprüfung der Wallbox gebraucht, weil die Autos hier "cloudfrei" sind. 

<img width="349" height="426" alt="image" src="https://github.com/user-attachments/assets/2eadc9f6-172c-4cba-a4ed-a27a6660c583" />

**Reply by thecem** [reply]
bitte mal die attribute posten

**Reply by typxxi** [reply]
### Meinst Du diese Liste hier ? 

Bei der Wallbox geh ich davon aus, dass das von Octopus aus der Anmeldung / Verknüpfung mit der Wallbox kommt. 
Stört mich an sich nicht wirklich, weil es ja "funktioniert", wie es im Moment scheint. 

```
planned_dispatches: 
completed_dispatches: 
- start: '2025-11-13T02:00:00+00:00'
  end: '2025-11-13T02:15:00+00:00'
  start_time: '2025-11-13 03:00:00'
  end_time: '2025-11-13 03:15:00'
  charge_kwh: 0
  source: null
  location: AT_HOME
- start: '2025-11-13T01:45:00+00:00'
  end: '2025-11-13T02:00:00+00:00'
  start_time: '2025-11-13 02:45:00'
  end_time: '2025-11-13 03:00:00'
  charge_kwh: 0
  source: null
  location: AT_HOME
- start: '2025-11-13T01:30:00+00:00'
  end: '2025-11-13T01:45:00+00:00'
  start_time: '2025-11-13 02:30:00'
  end_time: '2025-11-13 02:45:00'
  charge_kwh: 0
  source: null
  location: AT_HOME

devices: 
- id: 00000000-0009-4000-803c-00000000077f
  name: Wallbox Pulsar Max
  device_type: ELECTRIC_VEHICLES
  provider: OCPP_WALLBOX
  status: SMART_CONTROL_NOT_AVAILABLE
  is_suspended: false
  preferences:
    mode: CHARGE
    schedules:
      - day: MONDAY
        time: '05:00:00'
        min: null
        max: 30
      - day: TUESDAY
        time: '05:00:00'
        min: null
        max: 30
      - day: WEDNESDAY
        time: '05:00:00'
        min: null
        max: 30
      - day: THURSDAY
        time: '05:00:00'
        min: null
        max: 30
      - day: FRIDAY
        time: '05:00:00'
        min: null
        max: 30
      - day: SATURDAY
        time: '05:00:00'
        min: null
        max: 30
      - day: SUNDAY
        time: '05:00:00'
        min: null
        max: 30

current_state: SMART_CONTROL_NOT_AVAILABLE
last_updated: 2025-11-13T14:43:01.456986
friendly_name: OCTOPUS - 2.1 - INTELLIGENTER LADEPLAN
```
