### DISCUSSION TITLE
More user-friendly entry method for the target charge state

### DISCUSSION THREAD

**Discussion by benniju** [thecem/octopus_germany#28] [Show and tell]
I find the action pretty complicated to use. Because of this, I created these two extra entities:
1. Add a input_datetime.octopus_intelligent_endzeit
![input_datetime](https://github.com/user-attachments/assets/3ef85766-0360-42c2-90ff-9282dfa55de2)
2. Add a template number:
![grafik](https://github.com/user-attachments/assets/2b0b1b5a-9b8f-487c-89e4-282f55d3f673)

Code for the Value-Template:
```
{%- set sensor_name = 'binary_sensor.octopus_a_xxxxxxx_intelligent_dispatching' %}
{% set device = state_attr(sensor_name, 'devices')[0] %}
{% set schedules = device.preferences.schedules %}
{{ schedules[0].max }}
```
Code for the action (the action needs to be selected manually and then be switched to YAML-Mode):
```
action: octopus_germany.set_vehicle_charge_preferences
data_template:
  weekday_target_soc: "{{ value }}"
  weekend_target_soc: "{{ value }}"
  weekday_target_time: "{{ states('input_datetime.octopus_intelligent_endzeit').split(':')[:2] | join(':') }}"
  weekend_target_time: "{{ states('input_datetime.octopus_intelligent_endzeit').split(':')[:2] | join(':') }}"
```
### Main Caveats:
1. The time will only be set if the target is also changed after the time. Also it does not get updated if it is changed in any other way like with the App.
2. The value of the number entity is always the value for Monday. Also this solution does not allow setting a different target and time for weekday and weekend. But this is also not possible in the official Octopus App.

**Comment by thecem** [comment]
You expand your automation with:

```yaml
service: input_number.set_value
target:
  entity_id: input_number.vehicle_weekday_target_soc
data:
  value: >
    {{ state_attr('binary_sensor.octopus_a_12345678_intelligent_dispatching', 'devices')[0]['preferences']['schedules'][0]['max'] }}

```

and

```yaml

service: input_datetime.set_datetime
target:
  entity_id: input_datetime.vehicle_weekday_target_time
data:
  time: >
    {{ state_attr('binary_sensor.octopus_a_12345678_intelligent_dispatching', 'devices')[0]['preferences']['schedules'][0]['time'] }}
```
so every minute your input helper will be updated and present the actual settings. !pls post your working settings!

**Comment by thecem** [comment]
```yaml
alias: Octopus Target Time & SOC
description: ""
triggers:
  - entity_id: input_number.octopus_target_soc
    trigger: state
    id: to-API-soc
  - entity_id: input_datetime.octopus_target_time
    trigger: state
    id: to-API-time
  - trigger: state
    entity_id:
      - binary_sensor.octopus_a_66df80ae_intelligent_dispatching
    attribute: devices
    id: from-API
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - from-API
        sequence:
          - target:
              entity_id: input_number.octopus_target_soc
            data:
              value: >
                {{
                state_attr('binary_sensor.octopus_a_12345678_intelligent_dispatching',
                'devices')[0]['preferences']['schedules'][0]['max'] }}
            action: input_number.set_value
          - target:
              entity_id: input_datetime.octopus_target_time
            data:
              time: >
                {{
                state_attr('binary_sensor.octopus_a_12345678_intelligent_dispatching',
                'devices')[0]['preferences']['schedules'][0]['time'] }}
            action: input_datetime.set_datetime
      - conditions:
          - condition: trigger
            id:
              - to-API-soc
              - to-API-time
        sequence:
          - data_template:
              weekday_target_soc: "{{ states('input_number.octopus_target_soc') }}"
              weekend_target_soc: "{{ states('input_number.octopus_target_soc') }}"
              weekday_target_time: >-
                {{ states('input_datetime.octopus_target_time').split(':')[:2] |
                join(':') }}
              weekend_target_time: >-
                {{ states('input_datetime.octopus_target_time').split(':')[:2] |
                join(':') }}
            action: octopus_germany.set_vehicle_charge_preferences
mode: restart

```
