### ISSUE TITLE
Set vehicle charge preferences not working when using UI Mode

### ISSUE THREAD

**Issue by benniju** [thecem/octopus_germany#26]
### Describe the bug

When I try to use the action octopus_germany.set_vehicle_charge_preferences while entering the time in the UI Mode it does not work and I get an error in the Log.
It does work when manually writing the time in the YAML Mode like this:
```
action: octopus_germany.set_vehicle_charge_preferences
data:
  weekday_target_soc: 82
  weekday_target_time: "09:00"
  weekend_target_time: "09:00"
  weekend_target_soc: 82

```
So it appears that the Octopus API is expecting a time in the format HH:MM and not HH:MM:SS while the UI only allows the second input type.

### Steps to reproduce

1. Select the Action Octopus Germany: Set vehicle charge preferences
2. Change to UI-Mode
3. 
![Image](https://github.com/user-attachments/assets/5914a4cf-12e6-4ab1-b9ef-ace08c5e2e15)
5. Start the Action

### Log details

```text
2025-04-27 14:51:39.423 ERROR (MainThread) [custom_components.octopus_germany.octopus_germany] API error setting vehicle charge preferences: Serializer validation error. (code: KT-CT-4321)
2025-04-27 14:51:39.424 ERROR (MainThread) [custom_components.octopus_germany] Failed to set vehicle charge preferences
```

### Version

v0.0.51

**Comment by benniju** [comment]
As I am not such a good python programmer, I asked ChatGPT for a way to format that time in the right way. It work well though, and it also prevents a GraphQL-Injection (like a SQL-Injection) by ensuring the right format.

This is the code it added before the query formatting line:
```
        # Format times to HH:MM
        try:
            weekday_target_time = datetime.strptime(weekday_target_time, "%H:%M:%S").strftime("%H:%M")
        except ValueError:
            try:
                weekday_target_time = datetime.strptime(weekday_target_time, "%H:%M").strftime("%H:%M")
            except ValueError:
                _LOGGER.error(f"Invalid weekday_target_time format: {weekday_target_time}")
                return False

        try:
            weekend_target_time = datetime.strptime(weekend_target_time, "%H:%M:%S").strftime("%H:%M")
        except ValueError:
            try:
                weekend_target_time = datetime.strptime(weekend_target_time, "%H:%M").strftime("%H:%M")
            except ValueError:
                _LOGGER.error(f"Invalid weekend_target_time format: {weekend_target_time}")
                return False

```

**Comment by thecem** [comment]
The selector UI options are limited in HA, so we could not prevent the seconds.

The Action description is straight forward and the action example shows how it works.

```yaml

action: octopus_germany.set_vehicle_charge_preferences
data:
  weekday_target_soc: 65
  weekend_target_soc: 65
  weekday_target_time: "05:00"
  weekend_target_time: "05:00"
```
Is since it is implement working, I never assumed that this will be a problem.

Since 0.0.52 it is failsave

```yaml

action: octopus_germany.set_vehicle_charge_preferences
data:
  weekday_target_soc: 65
  weekend_target_soc: 65
  weekday_target_time: "05:02:55"
  weekend_target_time: "05:33:09"
```
This will be adapted as `"05:02"` and `"05:33"`

```yaml

action: octopus_germany.set_vehicle_charge_preferences
data:
  weekday_target_soc: 122
  weekend_target_soc: 65
  weekday_target_time: "05:02:55"
  weekend_target_time: "05:33:09"
```
Will end in an error and not submitted to the API at all.
