### ISSUE TITLE
Automations: Cannot select 'On' and 'Off' states

### ISSUE THREAD

**Issue by cschlipf** [thecem/octopus_germany#4]
Looking at the `Octopus Intelligent Dispatching` Entity it shows the various states:

<img width="614" alt="Image" src="https://github.com/user-attachments/assets/49458ee8-881a-4e69-b3ec-be59249bcd5f" />

However when trying to create an Automation that wants to listen for these states, the states are not selectable:

<img width="1071" alt="Image" src="https://github.com/user-attachments/assets/661fe7e2-dc15-469f-9efe-b0e66335826b" />

**Comment by thecem** [comment]
U have to enter by your own. Could you Pls give me a example sensor (maybe a standard HA one) and show me the attributes of this sensor?

**Comment by cschlipf** [comment]
Examples from MQTT with selectable values:

```yaml
  binary_sensor:
    - name: evcc_lp_1_enabled
      unique_id: uniqueid__evcc_lp_1_enabled
      icon: mdi:ev-station
      state_topic: "evcc/loadpoints/1/enabled"
      payload_on: "true"
      payload_off: "false"
      #device_class: problem
      availability_topic: "evcc/status"
```

One thing I noticed: Your sensor seems to be of the wrong type. It's a standard sensor:

<img width="614" alt="Image" src="https://github.com/user-attachments/assets/5ba83f67-c92e-44d4-9136-479dcaff3d0c" />

Whereas the one above is a binary_sensor

<img width="611" alt="Image" src="https://github.com/user-attachments/assets/07570c30-b419-4cca-ae57-70a1b2424980" />
